### PR TITLE
Handle both quoted names and unquoted names

### PR DESCRIPTION
**Pull request by pwagland**
Handle both " quoted names and unquoted names. Pass through the path so that the end user can see which file is not being parsed as expected. Ignore comment lines in .gitattributes.

### CODE REVIEW

**Comment by pwagland** [comment]
This should probably also be done in the other tasks that also look at .gitattributes.

**Comment by coldfix** [comment]
Hi, thanks! It's definitely true that the function so far doesn't consider leading/trailing whitespace, empty lines or C-style quoting.

However, since the regex and conditional code looks a bit ugly, I'd like to be sure to get it right before merging:

- IMO, a structure `if (cond) { FOO } else {BAR; return}` is better expressed (easier to read) as `if (not a) {BAR; return} FOO`
-  use raw strings for regex (`r'...'`) to avoid the need to escape backslashes.
- if executing a regex like this over and over, it should be pre-compiled for performance reason, i.e. store `GITTATTR_LINE = re.compile(r'...')` as a global.
- passing the object path is IMO not very useful as it should always be `.gitattributes`. More useful would be the object hash if anything (so the user could theoretically `git cat-file -p HASH` the whole file or search in which commits/trees it is present)
- IMO, the regex `^\s*((?:[^"]\S*)|(?:"(?:\\"|[^"])+(?<=[^\\])"))(.+)$` is too hard to read and understand. Also, the regex doesn't handle empty lines and its second part is not entirely correct. It will e.g. not recognize the valid C-string `"\\"`. I think, the part that recognizes C-strings should in fact look more like this:

```
"(\\.|[^\\"])*"
```

Best, Thomas

**Comment by coldfix** [comment]
I think I will do bit of cleanup myself based on your commit. Thanks!

**Comment by pwagland** [comment]
That also works for me :-) Happy for you to look into it further, I just noticed while reading up on .gitattributes that the "C-style" strings were possible. I'll close this, and leave it for you to push your changes through.

**Pull request closed without merging**
